<?php
declare(strict_types=1);

namespace Aavirbhava\AdsAnalytics\Model\ResourceModel;

use Magento\Framework\Model\ResourceModel\Db\AbstractDb;

class OrderAttribution extends AbstractDb
{
    protected function _construct(): void
    {
        $this->_init('ads_analytics_order_attribution', 'order_id');

        // REQUIRED for this table, and easy to miss.
        //
        // The primary key here is order_id — supplied by us, not generated by
        // an auto-increment. AbstractDb::isObjectNotNew() is
        //     $object->getId() !== null && (!$this->_useIsObjectNew || ...)
        // so with the default _useIsObjectNew = false, merely HAVING an id
        // makes Magento treat the row as pre-existing. It then issues
        // UPDATE ... WHERE order_id = <id>, matches zero rows, and returns
        // successfully having written nothing — no exception, no warning.
        //
        // Setting this to true at least makes save() honour isObjectNew().
        // NOTE it is still not enough on its own: saveNewObject() unsets the
        // id field before inserting (it assumes auto-increment), so a row
        // saved through the model lands with order_id = 0. That is why
        // Model\Service\OrderAttributionWriter writes this table with
        // insertOnDuplicate instead of the ORM. The flag stays for the
        // benefit of any future code that does go through the model.
        $this->_useIsObjectNew = true;
    }
}
